{{- if eq .Values.mode "harvester" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.harvester.kubeconfigSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loadbalancer-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  kubeconfig: |
    {{- .Values.harvester.kubeconfig | nindent 4 }}
{{- end }}

