apiVersion: v1
kind: Secret
metadata:
  name: openstack-creds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loadbalancer-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  OS_AUTH_URL: {{ .Values.openstackCreds.osAuthUrl | quote }}
  OS_USERNAME: {{ .Values.openstackCreds.osUsername | quote }}
  OS_PASSWORD: {{ .Values.openstackCreds.osPassword | quote }}
  OS_DOMAIN_NAME: {{ .Values.openstackCreds.osDomainName | quote }}
  OS_REGION_NAME: {{ .Values.openstackCreds.osRegionName | quote }}
  OS_PROJECT_ID: {{ .Values.openstackCreds.osProjectId | quote }}
