apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loadbalancer-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.dbCredentials.dbHost | quote }}
  DB_PORT: {{ .Values.dbCredentials.dbPort | quote }}
  DB_USER: {{ .Values.dbCredentials.dbUser | quote }}
  DB_PASSWORD: {{ .Values.dbCredentials.dbPassword | quote }}
  DB_NAME: {{ .Values.dbCredentials.dbName | quote }}
  DB_SSLMODE: {{ .Values.dbCredentials.dbSslmode | quote }}

