apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadbalancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: loadbalancer-controller
    {{- include "loadbalancer-controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: loadbalancer-controller
  ports:
    - name: grpc-notify
      protocol: TCP
      port: 50052
      targetPort: 50052
